import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sandip Olee || Developer 
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
       
      </Head>
      <main>
        <header>
          <nav>
            <ul>
              <li>
                <a href="#">About</a>
              </li>
              <li>
                <a href="#">Blog</a>
              </li>
              <li>
                <a href="#">Projects</a>
              </li>
            </ul>
          </nav>
        </header>
        <section className='hero-section'>
          <div>
            <p>Nameste  i am </p>
            <h2>Sandip Olee</h2>
            <p>Enthusiastic student 
of creativity</p>
          </div>
        </section>

      </main>
    </div>
  )
}
