import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Sandip Olee || Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main>
        <header>
          <nav>
            <ul>
              <li class="active-nav">
                <a href="#">About</a>
              </li>
              <li>
                <a href="#">Blog</a>
              </li>
              <li>
                <a href="#">Projects</a>
              </li>
            </ul>
          </nav>
        </header>
        <section class="hero-section ">
          <div class="container">
            <div class="hero-title">
              <h5 class="sub-title">Nameste I am </h5>
              <h2>Sandip Olee</h2>
              <p>Enthusiastic student</p>
              <p> of creativity</p>
              <button class="btn btn-one">Let’s Talk</button>
            </div>
          </div>

          <div class="cube"></div>
          <div class="cube"></div>
          <div class="cube"></div>
          <div class="cube"></div>
          <div class="cube"></div>
          <div class="cube"></div>
        </section>

        <section class="about">
          <div class="container v-center">
            <div class="title-text">
              <h2>ABOUT ME</h2>
            </div>
            <div class="body-text">
              <p>
                
                I’ve spent most of these years working across different areas of
                design like front-end development, landing pages, email design,
                app UI/UX, to my current role designing products for mobile
                platforms. Having worked on various projects that are already
                live, I can help you with the best possible suggestions and
                ideas that we can proceed with. With me, you aren’t forced to
                accept anything. I give you a variety of options we can work on
                together.
            
              </p>
            </div>
          </div>
        </section>
        <section id="projects">
          <div class="container ">
            <div class="title-text">
              <h2> MY PROJECTS</h2>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
